name: AllSigns
main: surva\allsigns\AllSigns
version: 1.0.11
api: [3.0.0,3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13,]

author: survanetwork
description: Turn signs into world teleport and command signs
website: https://github.com/survanetwork/AllSigns
